name: ext_utils
description: "ExtUtils is a Flutter package desiged to implement helpful utilities to make the development process quicker and easier."
version: 1.0.0
homepage: https://rillastudios.ca/
repository: https://github.com/RillaStudios/ext_utils
issue_tracker: https://github.com/RillaStudios/ext_utils/issues
funding: [https://www.buymeacoffee.com/izaakford]

environment:
  sdk: ^3.6.0-149.3.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
